### ISSUE TITLE
בדיקת מטלה 4

### ISSUE THREAD

**Issue by michael-lemberger** [ShmuelLa/Space-Prefab-Shooter#1]
הניסיון של התזוזה של השחקן כמו במשחק של אטארי אחלה רעיון, אבל לא שינית את הspawner
אז הוא יורה כל הזמן למעלה, קצת מאבד מהטעם שלו.
אחלה שיר השיר נושא של megalovania

**Comment by michael-lemberger** [comment]
אה אוקיי עכשיו אני מבין למה עשית מה שעשית. אבל חבל אולי היה מגניב לממש מה שאמרתי.
המטרה לברוח מהחלליות בצד בבילבול.

**Comment by ShmuelLa** [comment]
> אה אוקיי עכשיו אני מבין למה עשית מה שעשית. אבל חבל אולי היה מגניב לממש מה שאמרתי. המטרה לברוח מהחלליות בצד בבילבול.


כן לוקח השראה למטלה הבאה, תודה על המשוב!
שמח שאהבת את השיר :)
